Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Feedback*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*OneDrive*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*GetHelp*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Gaming*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*YourPhone*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Todo*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*GetStarted*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*BingNews*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*BingWeather*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Zune*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Outlook*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*AdvancedMicroDevicesInc-2.AMDRadeonSoftware*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.Xbox.TCUI'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.XboxApp'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.XboxGameOverlay'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.XboxIdentityProvider'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.XboxSpeechToTextOverlay'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'MicrosoftTeams'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.SkypeApp'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.MixedReality.Portal'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.Microsoft3DViewer'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.549981C3F5F10'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.MicrosoftSolitaireCollection'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.Wallet'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like '*Copilot*'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.Edge.GameAssist'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.PowerAutomateDesktop'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.MicrosoftOfficeHub'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.BingSearch'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
Get-AppxPackage -AllUsers | Where-Object {$_.Name -Like 'Microsoft.Print3D'} | Remove-AppxPackage -AllUsers -ErrorAction Continue
# View list of installed applications. Comment out if desired.
Get-AppxProvisionedPackage -Online | Where-Object {  $_.DisplayName -match $Junk  }| Format-Table  -Property DisplayName
